version: "3.5"

services:
    expo_android:
        container_name: fishing_app
        build: 
            context: .
            dockerfile: Dockerfile
        #env_file: .env
        command: npm start
        ports:
            - 19000:19000
            - 19001:19001
        volumes:
            - ${PWD}/:/fishing_app/